export const TEST_FACTORY_DEFAULTS = {
  ORDER: {
    TOTAL_PRICE: 10000,
    DISCOUNT_PRICE: 0,
    FINAL_PRICE: 10000,
    STATUS: "PENDING" as const,
  },
  ORDER_ITEM: {
    QUANTITY: 1,
    UNIT_PRICE: 10000,
    TOTAL_PRICE: 10000,
  },
} as const;
