/**
 * 애플리케이션 전체에서 사용되는 에러 코드
 * 도메인별로 중첩 구조로 관리하여 명확성과 유지보수성을 향상
 */
export const ErrorCode = {
  User: {
    Domain: {
      EMAIL_DUPLICATE: "EMAIL_DUPLICATE",
      INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
      INVALID_USER_NAME: "INVALID_USER_NAME",
    },
    Application: {
      NOT_FOUND: "USER_NOT_FOUND",
    },
  },

  Auth: {
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
  },

  Order: {
    Domain: {},
    Application: {
      NOT_FOUND: "ORDER_NOT_FOUND",
      INVALID_COUPON: "INVALID_COUPON",
      INSUFFICIENT_POINT_BALANCE: "INSUFFICIENT_POINT_BALANCE",
      PROCESSING_FAILED: "ORDER_PROCESSING_FAILED",
    },
  },

  Product: {
    Domain: {
      INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
      INVALID_QUANTITY: "INVALID_QUANTITY",
      INACTIVE_PRODUCT: "INACTIVE_PRODUCT",
      STOCK_RESERVATION_NOT_ACTIVE: "STOCK_RESERVATION_NOT_ACTIVE",
      STOCK_RESERVATION_EXPIRED: "STOCK_RESERVATION_EXPIRED",
      STOCK_RESERVATION_RELEASE_IDEMPOTENCY_KEY_MISMATCH:
        "STOCK_RESERVATION_RELEASE_IDEMPOTENCY_KEY_MISMATCH",
      STOCK_RESERVATION_CONFIRM_STOCK_IDEMPOTENCY_KEY_MISMATCH:
        "STOCK_RESERVATION_CONFIRM_STOCK_IDEMPOTENCY_KEY_MISMATCH",
    },
    Application: {
      NOT_FOUND: "PRODUCT_NOT_FOUND",
      STOCK_RESERVATION_NOT_FOUND: "STOCK_RESERVATION_NOT_FOUND",
      VALIDATION_ERROR: "PRODUCT_VALIDATION_ERROR",
    },
  },

  Wallet: {
    Domain: {
      INVALID_CHARGE_AMOUNT: "INVALID_CHARGE_AMOUNT",
      INVALID_USE_AMOUNT: "INVALID_USE_AMOUNT",
    },
    Application: {
      USER_BALANCE_NOT_FOUND: "USER_BALANCE_NOT_FOUND",
      POINT_TRANSACTION_NOT_FOUND: "POINT_TRANSACTION_NOT_FOUND",
      POINT_TRANSACTION_ALREADY_RECOVERED:
        "POINT_TRANSACTION_ALREADY_RECOVERED",
    },
  },

  Validation: {
    VALIDATION_ERROR: "VALIDATION_ERROR",
    BAD_REQUEST: "BAD_REQUEST",
  },

  Http: {
    NOT_FOUND: "NOT_FOUND",
    CONFLICT: "CONFLICT",
    UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY",
  },

  Coupon: {
    Domain: {
      INVALID_COUPON_CODE: "INVALID_COUPON_CODE",
      COUPON_EXPIRED: "COUPON_EXPIRED",
      COUPON_ALREADY_USED: "COUPON_ALREADY_USED",
      COUPON_NOT_ACTIVE: "COUPON_NOT_ACTIVE",
      COUPON_STOCK_EXHAUSTED: "COUPON_STOCK_EXHAUSTED",
      USER_COUPON_EXPIRED: "USER_COUPON_EXPIRED",
      USER_COUPON_ALREADY_USED: "USER_COUPON_ALREADY_USED",
      USER_COUPON_ALREADY_CANCELLED: "USER_COUPON_ALREADY_CANCELLED",
      USER_COUPON_ALREADY_RECOVERED: "USER_COUPON_ALREADY_RECOVERED",
    },
    Application: {
      COUPON_NOT_FOUND: "COUPON_NOT_FOUND",
      USER_COUPON_NOT_FOUND: "USER_COUPON_NOT_FOUND",
    },
  },

  Infrastructure: {
    DATABASE_CONNECTION_ERROR: "DATABASE_CONNECTION_ERROR",
    EXTERNAL_API_ERROR: "EXTERNAL_API_ERROR",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  },
} as const;
